#!/bin/bash
echo "Compiling...";
# npm install -g node-sass
node-sass src/scss/core.scss > hailstorm.css
echo "Prefixing...";
# npm install -g postcss-cli autoprefixer
postcss hailstorm.css --use autoprefixer -d ./
dos2unix hailstorm.css